# Configuration file for branch-based-snakes.py
# L1CAM Analysis - Sliding Window Processing Configuration

# Input/Output Directories
input_dir: "/Users/charlessander/Desktop/patzke lab computing/Sudhof Lab/L1CAM Analysis/making normalized cdf"
data_output_dir: "/Users/charlessander/Desktop/patzke lab computing/Sudhof Lab/Axon Analysis Pipeline/Data_Output"

# Output Organization
output_subdirs:
  images: "Images"              # For all image outputs (PNG, TIFF)
  plots: "Plots"               # For graphs and plots
  data: "Data"                 # For CSV files and data
  summaries: "Summaries"       # For summary files and reports
  debug: "Debug"               # For debug outputs

# Data Structure Configuration
use_hierarchical_structure: true  # Set to true for Group_X/Condition_Y structure
auto_detect_groups: true  # Automatically detect all Group_X folders
auto_detect_conditions: true  # Automatically detect all Condition_Y folders

# Analysis Parameters
min_sizes: [30]
conditions: []  # Will be auto-detected if auto_detect_conditions is true
groups: []  # Will be auto-detected if auto_detect_groups is true

# Color mapping for conditions (will be auto-generated if not specified)
colors: {}  # Will be auto-generated with distinct colors

# Image Processing Parameters
gaussian_sigma: 1.0
soma_gaussian_sigma: 5
distance_threshold: 15  # pixels for soma extraction
opening_disk_size: 20   # for soma mask refinement
dilation_disk_size: 20  # for soma mask safety margin

# Morphological Operations
opening_disk_size_filter: 2
closing_disk_size_filter: 1

# Spider Analysis Parameters
window_length: 20  # walk length from each branch point
pink_density_threshold: 0.05
pink_thickness_threshold: 3

# Legacy threshold parameters (used if use_regression_model is false)
# Note: Group names in replicate_offsets must match the biological replicate names (e.g., Group_A, Group_B, etc.)
percentile_threshold: 15
threshold_intercept: 82.5909
threshold_coefficient: 0.3027

# Replicate offsets - map your group names to their respective offsets
# Example: If your groups are named Group_A, Group_B, etc., use those exact names here
replicate_offsets:
  Group_A: -35  # Example offset for Group_A
  Group_B: 20   # Example offset for Group_B
  Group_C: -55  # Example offset for Group_C
  Group_D: 5    # Example offset for Group_D

# For legacy B114-style names, use the exact replicate identifier as the key
# replicate_offsets:
#   B114: -35
#   B115: 20
#   B116: -55
#   B117: 5

# Channel Names
fitc_channel_name: "FITC"
tritc_channel_name: "TRITC"

# Component Visualization Parameters
component_saturation: 0.8
component_value: 0.9
golden_ratio: 0.618033988749895

# Output Parameters
save_summary_plots: false  # Set to true to enable summary plot generation
dpi: 300
plot_dpi: 200